'use strict';
function pageMetadata(s){
  const lang=s.lang,ko=lang==='ko',tr=(en,k)=>ko?k:en,origin=SITE_CONFIG.origin,home=origin+ROUTES.path(lang,'story',1),p=ROUTES.path(lang,s.view,({story:s.chapter,chapter:s.chapter,song:s.song,album:s.album,map:s.place,characters:'all',character:s.character,archive:s.archive})[s.view]||'').split('?')[0],url=origin+p;
  let title=tr('JOSEON STORIES — nine albums, one story','조선 이야기 — 아홉 앨범, 하나의 이야기'),description=tr('Explore demosaii’s Joseon Stories: nine gugak hip-hop albums, 36 songs, 14 characters, the complete story and Korean lyrics with English translations.','demosaii의 조선 이야기. 아홉 국악힙합 앨범, 36곡, 14명의 인물. 이야기와 지도, 한국어 가사와 영어 번역을 만납니다.'),image='/assets/album-ch1.webp',entity=null,type='website';
  const albumName=id=>/^ch[1-9]$/.test(id)?(ko?ALBUMS[Number(id.slice(2))-1].ko:ALBUMS[Number(id.slice(2))-1].title):id==='ch0'?tr('Chapter 0: The Clown','0장: 광대'):'한판 · HANPAN';
  const artist={'@type':'Person','@id':origin+'/#demosaii',name:'demosaii',sameAs:['https://www.youtube.com/@demosaii']};
  if(s.view==='chapter'||s.view==='story'&&s.chapter>1){const a=ALBUMS[s.chapter-1];title=(ko?a.ko:a.title)+' — '+tr('Chapter '+a.id,'제'+a.id+'장');description=ko?KO_ALBUMS[a.id-1][2]:a.summary;image='/assets/album-ch'+a.id+'.webp';type='article';entity={'@type':'CreativeWork',name:ko?a.ko:a.title,position:a.id,inLanguage:lang,description,author:artist,isPartOf:{'@type':'CreativeWorkSeries',name:'조선 이야기 · JOSEON STORIES',url:home}};}
  if(s.view==='song'){const song=TRACKS.find(x=>x.id===s.song),album=song.id.startsWith('hp')?'hanpan':song.id.split('-')[0];title=(ko?song.ko:song.title)+' — '+tr('lyrics & translation','가사와 번역');description=tr(song.title+' — lyrics and Korean original. Track '+song.id.split('-')[1]+' of '+albumName(album)+' by demosaii.',song.ko+' — demosaii의 '+albumName(album)+' '+song.id.split('-')[1]+'번 트랙. 한국어 가사와 영어 번역.');image='/assets/album-'+album+'.webp';type='music.song';entity={'@type':'MusicRecording',name:song.ko,alternateName:song.title,inLanguage:'ko',position:Number(song.id.split('-')[1]),byArtist:artist,sameAs:song.listen,inAlbum:{'@type':'MusicAlbum',name:albumName(album),url:origin+ROUTES.path(lang,'album',album)},genre:album==='hanpan'?'Gugak House':'Gugak hip-hop',lyrics:{'@type':'CreativeWork',inLanguage:lang,text:ARCHIVE.lyrics[s.song].stanzas.map(st=>st[lang].join('\n')).join('\n\n')}};}
  if(s.view==='album'){title=albumName(s.album)+' — '+tr('album & lyrics','앨범과 가사');description=tr('Listen to '+albumName(s.album)+' by demosaii. Explore every track, read the Korean lyrics and English translations in order.',demosDescription(albumName(s.album)));image='/assets/album-'+s.album+'.webp';type='music.album';const songs=TRACKS.filter(x=>x.id.startsWith(s.album==='hanpan'?'hp-':s.album+'-'));entity={'@type':'MusicAlbum',name:albumName(s.album),byArtist:artist,numTracks:songs.length,inLanguage:'ko',genre:s.album==='hanpan'?'Gugak House':'Gugak hip-hop',track:songs.map(song=>({'@type':'MusicRecording',name:song.ko,alternateName:song.title,url:origin+ROUTES.path(lang,'song',song.id)}))};}
  if(s.view==='character'){const person=PEOPLE.find(x=>x.id===s.character);title=(ko?person.ko:person.name)+' — '+tr('character','등장인물');description=ko?KO_PEOPLE[person.id][1]:person.intro;image='/assets/'+person.id+'.webp';entity={'@type':'Person',name:ko?person.ko:person.name,description};}
  if(s.view==='characters'){title=tr('The 14 characters of JOSEON STORIES','조선 이야기의 인물 14명');description=tr('Meet the people in demosaii’s fictional Joseon: their chapters, songs and stories, with later events hidden until you choose to reveal them.','가상의 조선에 살아가는 사람들. 인물의 이야기와 등장하는 장, 노래를 찾아보세요. 이후의 이야기는 펼쳐야 볼 수 있습니다.');}
  if(s.view==='map'){const place=ARCHIVE.places[lang][s.place];title=place.ko+' — '+tr('story map','이야기 지도');description=place.text;image='/assets/map-base.webp';}
  if(s.view==='archive'){const meta={summary:['The story so far','줄거리','Read the story of Joseon Stories across all nine chapters. Contains spoilers.','아홉 장으로 이어지는 조선 이야기의 전체 줄거리. 주요 사건과 결말이 포함되어 있습니다.'],songs:['All 48 songs','전곡 48곡','Find every track in the main story, Chapter 0 and the independent HANPAN album.','본편 36곡, 탈쇠 기원 외전 4곡, 독립 앨범 한판 8곡의 가사와 음악.'],search:['Search the lyrics','가사 검색','Search 48 songs in Korean and English by a word, line or song title.','48곡의 한국어 가사와 영어 번역을 단어, 문장, 곡 제목으로 검색하세요.'],timeline:['Timeline','연표','Follow the chronology of the fictional Joseon Stories universe, from the palace to the northern front and beyond.','궁궐에서 북쪽 전선, 먼 훗날까지. 조선 이야기의 사건을 연표로 따라갑니다.'],ledger:['The journey of the ledger','그 종이가 거친 손들','Follow the ledger through nine keepers and places across Joseon Stories.','조선 이야기 속 장부가 거친 아홉 손과 자리를 따라갑니다.'],history:['Historical background','역사 노트','Historical institutions, customs and records behind the fictional world of Joseon Stories.','조선 이야기의 노래에 등장하는 제도와 풍습, 기록의 역사적 배경.'],book:['The complete book','조선 이야기 전자책','Read or download the complete Joseon Stories book in Korean or English, free.','조선 이야기의 전체 아홉 장을 한국어와 영어 전자책으로 무료로 읽거나 내려받으세요.'],contact:['Contact demosaii','demosaii에게 문의','Contact demosaii about Joseon Stories, music licensing, collaboration or corrections.','조선 이야기와 음악 사용, 협업, 수정 사항에 관해 demosaii에게 문의하세요.']}[s.archive];title=meta[ko?1:0];description=meta[ko?3:2];if(s.archive==='book')entity={'@type':'Book',name:'조선 이야기 · JOSEON STORIES',inLanguage:lang,author:artist,bookFormat:'https://schema.org/EBook',numberOfPages:ko?93:147,url:origin+'/book/'+(ko?'joseon-stories-kr.pdf':'joseon-stories.pdf')};}
  if(s.view==='worlds'){title=tr('JOSEON STORIES, CIRCUIT GUGAK and HANPAN','조선 이야기, 서킷 국악, 한판');description=tr('Three separate projects by demosaii: historical Joseon fiction, the future-Joseon world of CIRCUIT GUGAK, and the standalone Gugak House album HANPAN.','demosaii의 서로 다른 프로젝트. 조선 배경의 조선 이야기, 미래 조선의 서킷 국악, 독립 국악 하우스 앨범 한판.');}
  const id=({story:s.chapter,chapter:s.chapter,song:s.song,album:s.album,map:s.place,characters:'all',character:s.character,archive:s.archive})[s.view]||'';
  const alternate={ko:origin+ROUTES.path('ko',s.view,id),en:origin+ROUTES.path('en',s.view,id)};alternate['x-default']=alternate.ko;
  const fullTitle=title+(title.includes('JOSEON STORIES')||title.startsWith('조선 이야기 —')?'':' | '+tr('JOSEON STORIES','조선 이야기'));
  const webpage={'@type':'WebPage','@id':url+'#page',url,name:fullTitle,description,inLanguage:lang,isPartOf:{'@id':origin+'/#website'},...(entity?{mainEntity:{...entity,'@id':url+'#content',...(entity.url?{}:{url})}}:{})};
  return {title:fullTitle,description,image:origin+image,type,url,alternate,robots:SITE_CONFIG.mode==='public'&&!(s.view==='archive'&&s.archive==='search')?'index,follow,max-image-preview:large,max-snippet:-1':'noindex,nofollow',jsonld:{'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':origin+'/#website',name:'조선 이야기 · JOSEON STORIES',url:origin+'/',inLanguage:['ko','en'],creator:artist},webpage]}};
}
function demosDescription(name){return 'demosaii의 '+name+'. 수록곡을 순서대로 듣고 한국어 가사와 영어 번역을 읽어보세요.'}
function updateMetadata(){const m=pageMetadata(state);document.title=m.title;function meta(attr,key,value){let el=document.head.querySelector(`meta[${attr}="${key}"]`);if(!el){el=document.createElement('meta');el.setAttribute(attr,key);document.head.appendChild(el)}el.setAttribute('content',value)}function link(rel,url,lang){let sel=`link[rel="${rel}"]`+(lang?`[hreflang="${lang}"]`:''),el=document.head.querySelector(sel);if(!el){el=document.createElement('link');el.setAttribute('rel',rel);if(lang)el.setAttribute('hreflang',lang);document.head.appendChild(el)}el.setAttribute('href',url)}meta('name','description',m.description);meta('name','robots',m.robots);meta('name','author','demosaii');for(const [key,value] of Object.entries({title:m.title,description:m.description,type:m.type,url:m.url,image:m.image,'image:alt':m.title,site_name:'조선 이야기 · JOSEON STORIES',locale:state.lang==='ko'?'ko_KR':'en_US','locale:alternate':state.lang==='ko'?'en_US':'ko_KR'}))meta('property','og:'+key,value);for(const [key,value] of Object.entries({card:'summary_large_image',title:m.title,description:m.description,image:m.image}))meta('name','twitter:'+key,value);link('canonical',m.url);for(const [lang,url] of Object.entries(m.alternate))link('alternate',url,lang);let schema=document.querySelector('#page-schema');if(!schema){schema=document.createElement('script');schema.id='page-schema';schema.type='application/ld+json';document.head.appendChild(schema)}schema.textContent=JSON.stringify(m.jsonld).replace(/</g,'\\u003c');}
